### Send POST request with json body
POST http://localhost:8080/v1/libraryevent
Content-Type: application/json

{
  "libraryEventId": null,
  "libraryEventType": "NEW",
  "book": {
    "bookId": 456,
    "bookName": "Kafka using Spring Boot",
    "bookAuthor": "Dilip"
  }
}
